oss:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  acceessKeyId: LTAI4FtQbho4RQgVL7bgL4ZG
  accessKeySecret: HhPY51r7FUzdpPrccqqIG7DKrEqX1H
  bucketName: oss-xl.oss-cn-hangzhou.aliyuncs.com
  filePath: file-service
server:
  port: 9000
